### ISSUE TITLE
AH History and Stacks/Singles

### ISSUE THREAD

**Issue by montijin** [EdenServer/eden-web#6]
The auction house history under character sheets doesn't differentiate whether someone bought a stack or a single from the auction house when applicable. 
![image](https://user-images.githubusercontent.com/2160211/77091530-b2172300-69d6-11ea-8e89-8d878513edd2.png)

**Comment by bkesecker** [comment]
Fixed with Show Stacks button.

**Comment by slassen** [comment]
He’s talking about showing stacks or singles In player history. This is not resolved.
